[package]
name = "simplefs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfs_lib = { path = "./sfs_lib" }
serde_json = "*"
sha2 = '0.10.2'
